### ISSUE TITLE
Adding rule discription how to play

### ISSUE THREAD

**Issue by xstable** [devsargam/SnakeGame#39] opened 2022-10-12 11:21 UTC
Sure, Snake is an well known easy game. 
But every game should have a short description what to do at least, and which keys are to use.

Please assign it to me, and I'll add it in a nice way.

**Comment by devsargam** [comment] 2022-10-12 11:29
Great idea!

**Comment by jatin00000** [comment] 2022-10-12 16:18
I had solved the above issue. https://github.com/devsargam/SnakeGame/pull/45
Please accept my Merge Request.

**Comment by devsargam** [comment] 2022-10-12 16:39
@jatin00000 teaching how to play was supposed to be on website no on the readme

**Comment by jatin00000** [comment] 2022-10-13 03:29
I had added "How to Play" on Website.
https://github.com/devsargam/SnakeGame/pull/52

**Comment by jatin00000** [comment] 2022-10-13 17:14
I am sorry for the inconvenience caused by me. The pull request created by me earlier has a lot of resolve conflicts.
So, it would have been created a trouble.

**Comment by jatin00000** [comment] 2022-10-13 17:16
So I am making this new pull request https://github.com/devsargam/SnakeGame/pull/56 .
I had created the menu as required. 
Please review and accept my pull request.
Please assign this new pull request with all the earlier tags.
Thank You

**Comment by devsargam** [comment] 2022-10-13 17:23
@jatin00000 there was a lot of hussle. ATEOTD you did it :clinking_glasses: 
I will review the code tomorrow and merge it then.

**Closed** 2022-10-14 04:03 UTC
Labels: documentation, enhancement, good first issue, hacktoberfest
